services:
  app:
    build:
      context: .
#    command:
#      - "gunicorn"
#      - "django_project_site.wsgi:application"
#      - "--bind"
#      - "0.0.0.0:8000"
    command:
      sh -c "
              python manage.py collectstatic --noinput &&
              gunicorn django_project_site.wsgi:application --bind 0.0.0.0:8000
            "
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    volumes:
      - ./django_project_site/database:/app/database
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"

#    logging:
#      driver: loki
#      options:
#        loki-url: http://localhost:3100/loki/api/v1/push
##        loki-url: http://host.docker.internal:3100/loki/api/v1/push # don't work

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./django_project_site/static/:/static/  # Монтируем статические файлы
    ports:
      - "80:80"
    depends_on:
      - app

#  grafana:
#    image:
#      grafana/grafana:9.2.15
#    environment:
#      - GF_AUTH_ANONYMOUS_ENABLED=true
#      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
#    ports:
#      - "3000:3000"
#
#
#  loki:
#    image:
#      grafana/loki:2.8.0
#    ports:
#      - "3100:3100"
