# Generated by Django 5.1.5 on 2025-01-26 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0011_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
    ]
